openapi: 3.1.0
info:
  title: "bakutan-memory-archive"
  description: "Save and load the memory of bakutan"
  version: 1.0.0
servers:
  - url: "https"
paths:
  /memory:
    get:
      summary: "Get memory, definition is wip"
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  memories:
                    type: "array"
                    items:
                      $ref: "schema/memory.yaml"
    post:
      summary: "Save memory, definition is wip"
      requestBody:
        description: "Memory"
        content:
          application/json:
            schema:
              type: "object"
              properties:
                memory:
                  $ref: "schema/memory.yaml"
      responses:
        '200':
          description: "OK"
  /memory/{id}:
    get:
      summary: "Get memory"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        '200':
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  memory:
                    $ref: "schema/memory.yaml"
  /memory/byEventId/{eventId}:
    get:
      summary: "Get memory by eventKey"
      parameters:
        - name: "eventKey"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        '200':
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  memories:
                    type: "array"
                    items:
                      $ref: "schema/memory.yaml"
