name: deploy project to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: '20.10.0'

      - name: Install dependencies
        run: npm ci

      - name: Generate
        run: npm run build

      - name: Copy index.html for SPA
        run: cp ./dist/index.html ./dist/404.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./dist
